version: '3.8'

services:
  backend1:
    build:
      context: ./backend
    environment:
      - PORT=3001
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - INSTANCE=backend1
    networks:
      - internal

  backend2:
    build:
      context: ./backend
    environment:
      - PORT=3002
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - INSTANCE=backend2
    networks:
      - internal

  backend3:
    build:
      context: ./backend
    environment:
      - PORT=3003
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - INSTANCE=backend3
    networks:
      - internal

  proxy:
    image: openresty/openresty:alpine
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "443:443"
      - "80:80"
    networks:
      - internal
    depends_on:
      - backend1
      - backend2
      - backend3

networks:
  internal:
